/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package relief;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;

/**
 *
 * @author computer
 */
public class EmpPanel extends javax.swing.JFrame {

    /**
     * Creates new form EmpPanel
     */
    DefaultTableModel modela;
    DefaultTableModel modelb;
    public EmpPanel() {
        initComponents();
        modela=(DefaultTableModel)dtable.getModel();
        modelb=(DefaultTableModel)vtable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emplab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        firstpan = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fpan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fpan1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        en1 = new javax.swing.JTextField();
        ea1 = new javax.swing.JTextField();
        ep1 = new javax.swing.JTextField();
        ec1 = new javax.swing.JTextField();
        eamt1 = new javax.swing.JTextField();
        vpan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ag = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sub1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        rst1 = new javax.swing.JButton();
        cn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cbox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();
        gend = new javax.swing.JComboBox();
        dpan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        don = new javax.swing.JButton();
        volbutt = new javax.swing.JButton();
        p_donation = new javax.swing.JButton();
        jpan2 = new javax.swing.JPanel();
        dpanel = new javax.swing.JScrollPane();
        dtable = new javax.swing.JTable();
        vpanel = new javax.swing.JScrollPane();
        vtable = new javax.swing.JTable();
        rest = new javax.swing.JButton();
        p_vol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disaster Relief Monitoring System - Employee Panel");
        setResizable(false);

        emplab.setBackground(new java.awt.Color(255, 255, 204));
        emplab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emplab.setForeground(new java.awt.Color(255, 0, 0));
        emplab.setText("      EMPLOYEE");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Fund Entry");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Volunteer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Display Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pan2.setLayout(new java.awt.CardLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\computer\\Desktop\\globe.png")); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("Disaster Relief Monitoring System");

        javax.swing.GroupLayout firstpanLayout = new javax.swing.GroupLayout(firstpan);
        firstpan.setLayout(firstpanLayout);
        firstpanLayout.setHorizontalGroup(
            firstpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpanLayout.createSequentialGroup()
                .addGroup(firstpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpanLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel18))
                    .addGroup(firstpanLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        firstpanLayout.setVerticalGroup(
            firstpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpanLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pan2.add(firstpan, "card2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Donation Entries");

        fpan1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Name:");

        jLabel3.setText("Address:");

        jLabel5.setText("Phone:");

        jLabel6.setText("Country:");

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel7.setText("Amount:");

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fpan1Layout = new javax.swing.GroupLayout(fpan1);
        fpan1.setLayout(fpan1Layout);
        fpan1Layout.setHorizontalGroup(
            fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpan1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fpan1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(en1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fpan1Layout.createSequentialGroup()
                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(fpan1Layout.createSequentialGroup()
                                .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fpan1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(submit)
                                        .addGap(35, 35, 35)
                                        .addComponent(reset))
                                    .addGroup(fpan1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eamt1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ep1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ec1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fpan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ea1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addComponent(jLabel7))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        fpan1Layout.setVerticalGroup(
            fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpan1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fpan1Layout.createSequentialGroup()
                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(en1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eamt1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(52, 52, 52)
                .addGroup(fpan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(reset))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fpanLayout = new javax.swing.GroupLayout(fpan);
        fpan.setLayout(fpanLayout);
        fpanLayout.setHorizontalGroup(
            fpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpanLayout.createSequentialGroup()
                .addGroup(fpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fpanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fpanLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(fpan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        fpanLayout.setVerticalGroup(
            fpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(fpan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pan2.add(fpan, "card3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 51));
        jLabel11.setText("Volunteer Registration");

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setText("Age:");

        jLabel15.setText("Country:");

        jLabel8.setText("Gender:");

        sub1.setText("SUBMIT");
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Phone:");

        rst1.setText("RESET");
        rst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rst1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Address:");

        jLabel10.setText("Name:");

        cbox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A Positive", "B Positive", "A Negetive", "B Negetive", "AB Positive", "AB Negetive", "O Positive", "O Negetive" }));

        jLabel12.setText("Blood Group:");

        gend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sub1)
                        .addGap(18, 18, 18)
                        .addComponent(rst1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub1)
                    .addComponent(rst1))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout vpanLayout = new javax.swing.GroupLayout(vpan);
        vpan.setLayout(vpanLayout);
        vpanLayout.setHorizontalGroup(
            vpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpanLayout.createSequentialGroup()
                .addGroup(vpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vpanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vpanLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        vpanLayout.setVerticalGroup(
            vpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan2.add(vpan, "card4");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Data Display");

        don.setText("Donation Data");
        don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donActionPerformed(evt);
            }
        });

        volbutt.setText("Volunteer List");
        volbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volbuttActionPerformed(evt);
            }
        });

        p_donation.setText("Print Donation");
        p_donation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_donationActionPerformed(evt);
            }
        });

        jpan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpan2.setLayout(new java.awt.CardLayout());

        dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Country", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dpanel.setViewportView(dtable);

        jpan2.add(dpanel, "card2");

        vtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Gender", "Age", "Country", "Blood Group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vpanel.setViewportView(vtable);

        jpan2.add(vpanel, "card3");

        rest.setText("Reset Table");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });

        p_vol.setText("Print Volunteer");
        p_vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_volActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dpanLayout = new javax.swing.GroupLayout(dpan);
        dpan.setLayout(dpanLayout);
        dpanLayout.setHorizontalGroup(
            dpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanLayout.createSequentialGroup()
                .addGroup(dpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(dpanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 444, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dpanLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(don)
                .addGap(33, 33, 33)
                .addComponent(volbutt)
                .addGap(18, 18, 18)
                .addComponent(p_donation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_vol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dpanLayout.setVerticalGroup(
            dpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(dpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(don)
                    .addComponent(volbutt)
                    .addComponent(p_donation)
                    .addComponent(rest)
                    .addComponent(p_vol))
                .addGap(18, 18, 18)
                .addComponent(jpan2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        pan2.add(dpan, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emplab, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(emplab, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rst1ActionPerformed
        // TODO add your handling code here:
        ClearText();
    }//GEN-LAST:event_rst1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pan2.removeAll();
        pan2.repaint();
        pan2.revalidate();
        pan2.add(fpan);
        pan2.repaint();
        pan2.revalidate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pan2.removeAll();
        pan2.repaint();
        pan2.revalidate();
        pan2.add(vpan);
        pan2.repaint();
        pan2.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pan2.removeAll();
        pan2.repaint();
        pan2.revalidate();
        pan2.add(dpan);
        pan2.repaint();
        pan2.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ReliefLogin rlog = new ReliefLogin();
        rlog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donActionPerformed
        // TODO add your handling code here:
        jpan2.removeAll();
        jpan2.repaint();
        jpan2.revalidate();
        jpan2.add(dpanel);
        jpan2.repaint();
        jpan2.revalidate();
        
        String edname;
        String edadd;
        long edphone;
        long sum=0;
        int edamt;
        long total;
        String edcountry;
        
        try
        { 
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/relief","root","");
            Statement stmt=con.createStatement();
            ResultSet rst = stmt.executeQuery("select * from donation");       
            modela.setRowCount(0);
            while(rst.next())
            {
                edname = rst.getString("name");
                edadd = rst.getString("addr");
                edphone = rst.getLong("phone"); 
                edcountry = rst.getString("country");
                edamt = rst.getInt("amt");
                modela.addRow(new Object[]{edname, edadd, edphone,edcountry,edamt});
                sum=sum+edamt;               
            }
                
            modela.addRow(new Object[]{});    
            modela.addRow(new Object[]{null,null ,null ,"Total :",sum});
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_donActionPerformed

    private void volbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volbuttActionPerformed
        // TODO add your handling code here:
        jpan2.removeAll();
        jpan2.repaint();
        jpan2.revalidate();
        jpan2.add(vpanel);
        jpan2.repaint();
        jpan2.revalidate();
        
        String evname;
        String evadd;
        String evgen;
        long evphone;
        int evage;
        String evcountry;
        String evbgrp;
        int tvol=0;
        
        try
        { 
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/relief","root","");
            Statement stmt=con.createStatement();
            ResultSet rst = stmt.executeQuery("select * from volunteer"); 
            //ResultSet rs= stmt.executeQuery("select count(*) as total from donation");
            modelb.setRowCount(0);
            while(rst.next())
            {
                evname = rst.getString("name");
                evadd = rst.getString("addr");
                evphone = rst.getLong("phone"); 
                evcountry = rst.getString("country");
                evage = rst.getInt("age");
                evbgrp = rst.getString("blood_grp");
                evgen = rst.getString("gender");
                modelb.addRow(new Object[]{evname, evadd,evgen, evage, evphone, evcountry, evbgrp});
                tvol++;  
            }
            
            modelb.addRow(new Object[]{});
            modelb.addRow(new Object[]{null, null ,null , null , null ,"Total Volunteer:" , tvol});
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_volbuttActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        ClearText();

    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String edn=en1.getText();
        String eda=ea1.getText();
        String edp1=ep1.getText();
        String edamt1=eamt1.getText();
        Long edp=Long.parseLong(edp1);
        int edamt=Integer.parseInt(edamt1);
        String edc=ec1.getText();
        
        try
        { 
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/relief","root","");//"jdbc:oracle:thin:@localhost:1521:XE","jpt","jpt123");
            Statement stmt=con.createStatement();      
            stmt.executeUpdate("insert into donation values ('"+edn+"','"+eda+"'," +edp+ ",'"+edc+"'," +edamt+ ")");
            JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
            JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        // TODO add your handling code here:
        modela.setRowCount(0);
        modelb.setRowCount(0);        
    }//GEN-LAST:event_restActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
        String vn1=name.getText();
        String va1=add.getText();
        String vage1=ag.getText();
        String vp=ph.getText();
        Long vp1=Long.parseLong(vp);
        String vc1=cn.getText();
        int vage2=Integer.parseInt(vage1);
        String vcbox1=(String) gend.getSelectedItem();
        String vcbox2=(String) cbox1.getSelectedItem();
        
        try
        { 
            Class.forName("com.mysql.jdbc.Driver"); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/relief","root","");//"jdbc:oracle:thin:@localhost:1521:XE","jpt","jpt123");
            Statement stmt=con.createStatement();
            stmt.executeUpdate("insert into volunteer values('"+vn1+"','"+va1+"','"+vcbox1+"'," +vage2+ "," +vp1+ ",'"+vc1+"','"+vcbox2+"')");       
            JOptionPane.showMessageDialog(null,"Volunteer Data Inserted Successfully!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sub1ActionPerformed

    private void p_donationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_donationActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Donation Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
            dtable.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(PrinterException e)
        {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_p_donationActionPerformed

    private void p_volActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_volActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Volunteer Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
            vtable.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(PrinterException e)
        {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_p_volActionPerformed
    public void ClearText()
    {
            en1.setText("");
            ea1.setText("");
            ep1.setText("");
            eamt1.setText("");
            ec1.setText("");
            ag.setText("");
            add.setText("");
            cn.setText("");
            name.setText("");
            ph.setText("");
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField ag;
    private javax.swing.JComboBox cbox1;
    private javax.swing.JTextField cn;
    private javax.swing.JButton don;
    private javax.swing.JPanel dpan;
    private javax.swing.JScrollPane dpanel;
    private javax.swing.JTable dtable;
    private javax.swing.JTextField ea1;
    private javax.swing.JTextField eamt1;
    private javax.swing.JTextField ec1;
    private javax.swing.JLabel emplab;
    private javax.swing.JTextField en1;
    private javax.swing.JTextField ep1;
    private javax.swing.JPanel firstpan;
    private javax.swing.JPanel fpan;
    private javax.swing.JPanel fpan1;
    private javax.swing.JComboBox gend;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpan2;
    private javax.swing.JTextField name;
    private javax.swing.JButton p_donation;
    private javax.swing.JButton p_vol;
    private javax.swing.JPanel pan2;
    private javax.swing.JTextField ph;
    private javax.swing.JButton reset;
    private javax.swing.JButton rest;
    private javax.swing.JButton rst1;
    private javax.swing.JButton sub1;
    private javax.swing.JButton submit;
    private javax.swing.JButton volbutt;
    private javax.swing.JPanel vpan;
    private javax.swing.JScrollPane vpanel;
    private javax.swing.JTable vtable;
    // End of variables declaration//GEN-END:variables
}
